//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string BillingAddress { get; set; }
        public string CreditCardNumber { get; set; }
        public string Expirydate { get; set; }
        public string CVVCode { get; set; }
        public Nullable<bool> RegisteredUser { get; set; }
        public Nullable<bool> Guest { get; set; }
    }
}
